version: 2

sources:
  - name: fintech
    description: Raw fintech transaction data from payment processing platform
    
    tables:
      - name: raw_transactions
        description: >
          Raw transaction records from the payment gateway.
          Contains all payment attempts including successful and failed transactions.
        columns:
          - name: transaction_id
            description: Unique identifier for each transaction
            tests:
              - unique
              - not_null
          
          - name: merchant_id
            description: Foreign key to merchant
            
          - name: customer_id
            description: Foreign key to customer
            
          - name: amount
            description: Transaction amount in specified currency
            tests:
              - not_null
          
          - name: status
            description: Transaction status (completed, failed, pending)
      
      - name: raw_merchants
        description: >
          Merchant profile information including business details and account tier.
        columns:
          - name: merchant_id
            description: Unique merchant identifier
            tests:
              - unique
              - not_null
          
          - name: merchant_name
            description: Business name of the merchant
          
          - name: tier
            description: Account tier (standard, premium, enterprise)
      
      - name: raw_customers
        description: Customer profile and metadata
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
      
      - name: raw_fraud_flags
        description: >
          Fraud detection flags and risk signals.
          Generated by automated fraud detection systems.
        columns:
          - name: flag_id
            description: Unique flag identifier
            tests:
              - unique
              - not_null
          
          - name: transaction_id
            description: Associated transaction
          
          - name: severity
            description: Risk severity level (low, medium, high)
